[project]
sdk_version = "0.8.1"
name = "skull"

[entrypoint]
file_path = "assets/default.xex"
out_directory_path = "generated"
includes = [
  "skull_config.toml",
]

# Verify these??????
setjmp_address = 0x824A0CC0
longjmp_address = 0x824A0880
